/**
 * Manufacturing Process Guide — static content/data.
 * Every statement here mirrors the actual Bisonstechs implementation
 * (production order statuses/transitions, reservation/issue, output cap,
 * close-short reason, quality/rework/scrap/by-product/costing behavior and
 * the real frontend routes used for "Open Screen" links).
 */

export type ModuleKey = 'Warehouse' | 'Purchase' | 'Manufacturing' | 'Quality' | 'Costing';
export type InventoryKey = 'STOCK IN' | 'STOCK OUT' | 'RESERVE' | 'NO STOCK EFFECT' | 'RECORD';

export interface ModuleMeta {
  label: string;
  color: string;
  bg: string;
}

export const MODULES: Record<ModuleKey, ModuleMeta> = {
  Warehouse: { label: 'Warehouse', color: '#0FA3E0', bg: '#EAF7FD' },
  Purchase: { label: 'Purchase', color: '#F39C12', bg: '#FEF4E6' },
  Manufacturing: { label: 'Manufacturing', color: '#014582', bg: '#E7EFF8' },
  Quality: { label: 'Quality', color: '#8E44AD', bg: '#F3EBFA' },
  Costing: { label: 'Costing', color: '#2ECC71', bg: '#EAF9F0' },
};

export const INVENTORY: Record<InventoryKey, { color: string; bg: string }> = {
  'STOCK IN': { color: '#2ECC71', bg: '#EAF9F0' },
  'STOCK OUT': { color: '#E74C3C', bg: '#FDECEB' },
  RESERVE: { color: '#8E44AD', bg: '#F3EBFA' },
  'NO STOCK EFFECT': { color: '#7A8FA6', bg: '#F0F4F8' },
  RECORD: { color: '#F39C12', bg: '#FEF4E6' },
};

export type Phase =
  | 'BUY' | 'RECEIVE' | 'STOCK' | 'SETUP' | 'BOM' | 'ROUTING' | 'ORDER'
  | 'RELEASE' | 'RESERVE' | 'ISSUE' | 'PRODUCE' | 'OUTPUT' | 'QUALITY'
  | 'FG' | 'COST' | 'COMPLETE' | 'CLOSE' | 'REWORK' | 'SCRAP' | 'BYPRODUCT'
  | 'PARTIAL' | 'SHORT';

export interface GuideStep {
  id: string; // anchor
  num: string; // '01'
  title: string;
  summary: string;
  phase: Phase;
  module: ModuleKey;
  inventory: InventoryKey;
  icon: string;
  purpose: string;
  where: { screen: string; routes: string[] };
  whatUserDoes: string;
  statusBefore: string;
  action: string;
  statusAfter: string;
  dataCreated: string;
  inventoryEffect: string;
  accountingEffect?: string;
  whenWrong?: string;
  next: string;
  nextId?: string;
  openScreen?: string;
  childOf?: string; // parent concept, e.g. 'Production Order'
  childLabel?: string;
}

export const STEPS: GuideStep[] = [
  {
    id: 'step-supplier-purchase',
    num: '01',
    title: 'Supplier & Purchase',
    summary: 'Buy the raw materials you will later consume.',
    phase: 'BUY',
    module: 'Purchase',
    inventory: 'NO STOCK EFFECT',
    icon: 'ShoppingCart',
    purpose: 'Manufacturing consumes raw material, so you must first buy it. A supplier is created, then a Purchase Order lists what you intend to buy and from whom.',
    where: { screen: 'Purchases → Suppliers · Purchases → Purchase Order', routes: ['/purchases/suppliers', '/purchases/purchaseorder'] },
    whatUserDoes: 'Create the supplier, then create a Purchase Order with the raw-material items and quantities.',
    statusBefore: '(none) · Supplier Open',
    action: 'Create Purchase Order',
    statusAfter: 'Purchase Order Created / Approved',
    dataCreated: 'Supplier record, PurchaseOrder + PO items',
    inventoryEffect: 'None. A PO is intent to buy — it does not move stock into inventory.',
    accountingEffect: 'No posting at PO stage. The liability is recognised when you invoice/bill or receive.',
    whenWrong: 'If you under-order, the PO stays partially fulfilled — you still need a GRN to bring stock in.',
    next: 'Next → GRN / Goods Receiving',
    nextId: 'step-grn',
    openScreen: '/purchases/purchaseorder',
  },
  {
    id: 'step-grn',
    num: '02',
    title: 'GRN / Goods Receiving',
    summary: 'Physically receive the purchased material and bring stock in.',
    phase: 'RECEIVE',
    module: 'Purchase',
    inventory: 'STOCK IN',
    icon: 'PackageCheck',
    purpose: 'A Goods Receiving Note (GRN) records that the material physically arrived. Confirming it is the action that increases warehouse stock.',
    where: { screen: 'Purchases → Goods Receiving', routes: ['/purchases/goodsRecieving'] },
    whatUserDoes: 'Create the GRN from the PO (with received quantities), then Confirm it.',
    statusBefore: 'GRN Draft',
    action: 'Create GRN → Confirm',
    statusAfter: 'GRN Fully Received',
    dataCreated: 'GoodsReceiving + receiving items (receivingQuantity)',
    inventoryEffect: 'STOCK IN — on-hand of the received product increases in the receiving location.',
    accountingEffect: 'Inventory builds up; only the confirmed GRN moves stock.',
    whenWrong: 'Receiving more than the PO remaining is rejected; reduce the quantity or create another PO.',
    next: 'Next → Raw Material Stock',
    nextId: 'step-stock',
    openScreen: '/purchases/goodsRecieving',
  },
  {
    id: 'step-stock',
    num: '03',
    title: 'Raw Material Stock',
    summary: 'Confirm the material is physically available before production.',
    phase: 'STOCK',
    module: 'Warehouse',
    inventory: 'NO STOCK EFFECT',
    icon: 'Box',
    purpose: 'Manufacturing can only consume material that already exists in stock. This step verifies quantity before planning.',
    where: { screen: 'Warehouse → Locations / Stock', routes: ['/warehouse/locations', '/warehouse/stock-movement'] },
    whatUserDoes: 'Open the warehouse stock screen and check on-hand (currentStock) and available (availableStock) for each material.',
    statusBefore: '(stock rows present after the confirmed GRN)',
    action: 'Verify stock',
    statusAfter: 'Material available for manufacturing',
    dataCreated: 'None new — the stock rows already exist.',
    inventoryEffect: 'None here — a verification step only.',
    whenWrong: 'If available = 0, come back to Purchase + GRN first, because Release cannot reserve what is not there.',
    next: 'Next → Work Center',
    nextId: 'step-work-center',
    openScreen: '/warehouse/locations',
  },
  {
    id: 'step-work-center',
    num: '04',
    title: 'Work Center',
    summary: 'Define where production operations happen.',
    phase: 'SETUP',
    module: 'Manufacturing',
    inventory: 'NO STOCK EFFECT',
    icon: 'Users',
    purpose: 'A Work Center is the place/function where an operation runs (Cutting, Assembly, Packing). Its cost-per-hour feeds labor cost.',
    where: { screen: 'Manufacturing → Master → Work Centers', routes: ['/manufacturing/master/work-centers'] },
    whatUserDoes: 'Add a Work Center with a name, department, location, capacity and cost-per-hour.',
    statusBefore: '(none)',
    action: 'Add Work Center',
    statusAfter: 'Work Center Active',
    dataCreated: 'WorkCenter record',
    inventoryEffect: 'No stock effect.',
    next: 'Next → Machine',
    nextId: 'step-machine',
    openScreen: '/manufacturing/master/work-centers',
  },
  {
    id: 'step-machine',
    num: '05',
    title: 'Machine',
    summary: 'Define the equipment (linked to a Work Center).',
    phase: 'SETUP',
    module: 'Manufacturing',
    inventory: 'NO STOCK EFFECT',
    icon: 'Wrench',
    purpose: 'A Machine is the specific piece of equipment used by production. It is linked to a Work Center and has an hourly operating cost.',
    where: { screen: 'Manufacturing → Master → Machines', routes: ['/manufacturing/master/machines'] },
    whatUserDoes: 'Add a Machine, link it to a Work Center, enter its hourly operating cost and initial status.',
    statusBefore: '(none)',
    action: 'Add Machine',
    statusAfter: 'Machine Active / Idle',
    dataCreated: 'Machine record',
    inventoryEffect: 'No stock effect.',
    next: 'Next → BOM',
    nextId: 'step-bom',
    openScreen: '/manufacturing/master/machines',
  },
  {
    id: 'step-bom',
    num: '06',
    title: 'BOM (Bill of Materials)',
    summary: 'Define WHAT materials are required for one unit.',
    phase: 'BOM',
    module: 'Manufacturing',
    inventory: 'NO STOCK EFFECT',
    icon: 'Boxes',
    purpose: 'The BOM is the recipe: it lists every component and the quantity needed to make one finished unit, plus scrap % and estimated cost.',
    where: { screen: 'Manufacturing → Master → BOM', routes: ['/manufacturing/master/bom'] },
    whatUserDoes: 'Add a BOM for the finished product and add component lines (material, quantity, unit, scrap %, estimated cost).',
    statusBefore: '(none)',
    action: 'Add BOM + component lines',
    statusAfter: 'BOM Draft / Active',
    dataCreated: 'BOM + BOM components',
    inventoryEffect: 'No stock effect — planning data only.',
    whenWrong: 'Wrong quantity/unit leads to an incorrect material reservation at Release. Set it Active only when correct.',
    next: 'Next → Routing',
    nextId: 'step-routing',
    openScreen: '/manufacturing/master/bom',
  },
  {
    id: 'step-routing',
    num: '07',
    title: 'Routing',
    summary: 'Define HOW the product is produced step by step.',
    phase: 'ROUTING',
    module: 'Manufacturing',
    inventory: 'NO STOCK EFFECT',
    icon: 'Route',
    purpose: 'Routing lists the ordered operations that turn material into the finished product, each with a Work Center, Machine, times and cost.',
    where: { screen: 'Manufacturing → Master → Routings', routes: ['/manufacturing/master/routings'] },
    whatUserDoes: 'Add a Routing for the finished product and add operations in sequence (name, order, work center, machine, times, cost).',
    statusBefore: '(none)',
    action: 'Add Routing + operations',
    statusAfter: 'Routing Draft / Active',
    dataCreated: 'Routing + routing operations',
    inventoryEffect: 'No stock effect — planning data only.',
    whenWrong: 'Operation order matters: Work Orders are created in this sequence order at Release.',
    next: 'Next → Production Order',
    nextId: 'step-production-order',
    openScreen: '/manufacturing/master/routings',
  },
  {
    id: 'step-production-order',
    num: '08',
    title: 'Production Order',
    summary: 'Authorise manufacturing of a quantity of a finished product.',
    phase: 'ORDER',
    module: 'Manufacturing',
    inventory: 'NO STOCK EFFECT',
    icon: 'ClipboardList',
    purpose: 'The Production Order (the "MO") defines what you will make, how many units, from which warehouses, and which BOM/Routing to use.',
    where: { screen: 'Manufacturing → Production → Production Orders · New Order', routes: ['/manufacturing/production/orders', '/manufacturing/production/orders/new'] },
    whatUserDoes: 'Pick the product, planned quantity, source warehouse (required), WIP and finished-goods warehouses; BOM/Routing auto-fill from the Active versions.',
    statusBefore: '(none)',
    action: 'New Order → Create',
    statusAfter: 'Draft',
    dataCreated: 'ProductionOrder — produced = 0, remaining = planned',
    inventoryEffect: 'None. Creating an order reserves nothing.',
    accountingEffect: 'None yet.',
    whenWrong: 'If no source warehouse is set, Release will fail with "Source warehouse is required".',
    next: 'Next → Release',
    nextId: 'step-release',
    openScreen: '/manufacturing/production/orders/new',
  },
  {
    id: 'step-release',
    num: '09',
    title: 'Release',
    summary: 'Go live: reserve material, create Work Orders and WIP.',
    phase: 'RELEASE',
    module: 'Manufacturing',
    inventory: 'RESERVE',
    icon: 'Rocket',
    purpose: 'Release is the biggest "go" step: it reserves material, spawns one Work Order per Routing operation, creates a WIP record, and moves the order to Released.',
    where: { screen: 'Production Order detail → Release', routes: ['/manufacturing/production/orders'] },
    whatUserDoes: 'Open the order and press Release (a source warehouse must be set first).',
    statusBefore: 'Draft / Planned',
    action: 'Release',
    statusAfter: 'Released',
    dataCreated: 'Material reservations (1 per BOM component), Work Orders (1 per Routing operation), WIP record',
    inventoryEffect: 'RESERVE — reserved stock increases, available stock decreases, on-hand unchanged.',
    whenWrong: 'If stock is short, a reservation is created PartiallyReserved/Pending with a shortage — receive more material first.',
    next: 'Next → Material Reservation',
    nextId: 'step-reservation',
    openScreen: '/manufacturing/production/orders',
  },
  {
    id: 'step-reservation',
    num: '10',
    title: 'Material Reservation',
    summary: 'Material is held for this production order.',
    phase: 'RESERVE',
    module: 'Manufacturing',
    inventory: 'RESERVE',
    icon: 'PackageSearch',
    childOf: 'Production Order',
    childLabel: 'Child record',
    purpose: 'A confirmation that the ERP holds the required quantity so another process cannot consume it. One reservation line per BOM component.',
    where: { screen: 'Manufacturing → Materials → Reservations', routes: ['/manufacturing/materials/reservations'] },
    whatUserDoes: 'Verify each reservation: status should be Reserved (PartiallyReserved if short, Pending if nothing was available).',
    statusBefore: '(created at Release)',
    action: 'Verify reservations',
    statusAfter: 'Reservation Reserved / PartiallyReserved / Pending',
    dataCreated: 'MaterialReservation per component (required, available, reserved, shortage)',
    inventoryEffect: 'RESERVE — material is held (available drops), not removed.',
    whenWrong: 'A Pending reservation means material is not available — buy + GRN first.',
    next: 'Next → Material Issue',
    nextId: 'step-issue',
    openScreen: '/manufacturing/materials/reservations',
  },
  {
    id: 'step-issue',
    num: '11',
    title: 'Material Issue',
    summary: 'Material actually leaves the warehouse into production.',
    phase: 'ISSUE',
    module: 'Manufacturing',
    inventory: 'STOCK OUT',
    icon: 'FileUp',
    childOf: 'Production Order',
    childLabel: 'Child record',
    purpose: 'Issuing hands the reserved material to production. This is what decreases on-hand raw material stock and records the issue.',
    where: { screen: 'Manufacturing → Materials → Issues', routes: ['/manufacturing/materials/issues'] },
    whatUserDoes: 'From the order, Issue the selected lines (or issue all remaining). If negative inventory is off and qty exceeds on-hand, the system rejects.',
    statusBefore: 'Reservation Reserved; order Released',
    action: 'Issue Materials / Issue Selected Lines',
    statusAfter: 'Reservation Completed/PartiallyReserved; MaterialIssue Issued',
    dataCreated: 'MaterialIssue per line (issuedQuantity, from/to location)',
    inventoryEffect: 'STOCK OUT — on-hand decreases, reserved decreases by the issued quantity.',
    whenWrong: 'Issue types out an explicit error naming the on-hand and how much to reduce, or to receive stock first.',
    next: 'Next → Start Production',
    nextId: 'step-start',
    openScreen: '/manufacturing/materials/issues',
  },
  {
    id: 'step-start',
    num: '12',
    title: 'Start Production',
    summary: 'Mark the order as in progress.',
    phase: 'PRODUCE',
    module: 'Manufacturing',
    inventory: 'NO STOCK EFFECT',
    icon: 'Play',
    purpose: 'Once material is issued, Start moves the order from Released to In Progress so operations can be run.',
    where: { screen: 'Production Order detail → Start', routes: ['/manufacturing/production/orders'] },
    whatUserDoes: 'Press Start on the order (sets actualStartDate).',
    statusBefore: 'Released',
    action: 'Start',
    statusAfter: 'In Progress',
    dataCreated: 'actualStartDate',
    inventoryEffect: 'No direct stock effect (issues already accounted for material).',
    next: 'Next → Operations / Work Orders',
    nextId: 'step-operations',
    openScreen: '/manufacturing/production/orders',
  },
  {
    id: 'step-operations',
    num: '13',
    title: 'Operations / Work Orders',
    summary: 'Run the production steps in sequence.',
    phase: 'PRODUCE',
    module: 'Manufacturing',
    inventory: 'NO STOCK EFFECT',
    icon: 'ListTodo',
    childOf: 'Production Order',
    childLabel: 'Child record (created at Release)',
    purpose: 'Each Routing operation became a Work Order. Operators run them in sequence: Start → Report → Complete, then the next one.',
    where: { screen: 'Manufacturing → Production → Work Orders · Shop Floor', routes: ['/manufacturing/production/work-orders', '/manufacturing/production/shop-floor'] },
    whatUserDoes: 'Start a Work Order, Report quantities (good / rejected / scrap / downtime), then Complete it.',
    statusBefore: 'Work Order Pending',
    action: 'Start · Report · Complete',
    statusAfter: 'Work Order Completed',
    dataCreated: 'Work-order quantities, start/end time, downtime',
    inventoryEffect: 'No direct stock effect — material was already issued.',
    whenWrong: 'The operation only auto-completes when good + scrap + rejected ≥ planned. Report the real output on the operation where production finished.',
    next: 'Next → Production Output',
    nextId: 'step-output',
    openScreen: '/manufacturing/production/work-orders',
  },
  {
    id: 'step-output',
    num: '14',
    title: 'Production Output',
    summary: 'Roll up what was produced: good, rejected, scrap, remaining.',
    phase: 'OUTPUT',
    module: 'Manufacturing',
    inventory: 'NO STOCK EFFECT',
    icon: 'Box',
    purpose: 'Combine all operation reports into the order numbers: produced (good), rejected, scrap and the remaining quantity still to make.',
    where: { screen: 'Production Order → Output', routes: ['/manufacturing/production/orders'] },
    whatUserDoes: 'Review good = produced, rejected, scrap, remaining = planned − produced. Prepare for the FG receipt.',
    statusBefore: 'In Progress',
    action: 'Review output',
    statusAfter: 'Ready for FG receipt',
    dataCreated: 'Updated produced/rejected/scrap/remaining on the order',
    inventoryEffect: 'No finished-goods stock yet — that happens at the FG receipt.',
    whenWrong: 'If produced < planned, the order becomes Partially Completed — continue the same MO or Close Short.',
    next: 'Next → Quality Inspection / FG Receipt',
    nextId: 'step-quality',
    openScreen: '/manufacturing/production/orders',
  },
  {
    id: 'step-quality',
    num: '15',
    title: 'Quality Inspection',
    summary: 'Check the output against expected quality parameters.',
    phase: 'QUALITY',
    module: 'Quality',
    inventory: 'NO STOCK EFFECT',
    icon: 'SearchCheck',
    childOf: 'Production Order',
    childLabel: 'Child record (inspection)',
    purpose: 'An inspection records expected vs actual values for quality parameters and a result. Types: Incoming, InProcess, Final. Result: Pending, Passed, Failed, Rework, Scrap.',
    where: { screen: 'Manufacturing → Quality → Inspections', routes: ['/manufacturing/quality/inspections'] },
    whatUserDoes: 'Add an Inspection for the order (an HR inspector is required), enter parameters and save the result.',
    statusBefore: 'Inspection Pending',
    action: 'Add Inspection → Save',
    statusAfter: 'Inspection Passed / Failed / Rework / Scrap',
    dataCreated: 'QualityInspection + quality parameters',
    inventoryEffect: 'No stock effect.',
    whenWrong: 'On Failed, the follow-up is Rework (or Scrap). QC does not automatically change the production-order status on its own.',
    next: 'Pass → FG Receipt · Fail → Rework',
    nextId: 'step-fg',
    openScreen: '/manufacturing/quality/inspections',
  },
  {
    id: 'step-fg',
    num: '16',
    title: 'Finished Goods Receipt',
    summary: 'Receive the produced quantity into the finished-goods warehouse.',
    phase: 'FG',
    module: 'Manufacturing',
    inventory: 'STOCK IN',
    icon: 'PackagePlus',
    purpose: 'This is what physically brings finished goods into stock. It posts FG on-hand and sets the order to Completed (remaining 0) or Partially Completed.',
    where: { screen: 'Production Order → Output → Complete & Receive FG', routes: ['/manufacturing/production/orders'] },
    whatUserDoes: 'Enter the good quantity to receive (cap = remaining for the current receipt) and receive into the FG warehouse.',
    statusBefore: 'Released / In Progress / Paused / Partially Completed',
    action: 'Complete & Receive FG',
    statusAfter: 'Completed (remaining 0) or Partially Completed',
    dataCreated: 'FG stock-in; order producedQuantity/remaining; remaining reservations released when Completed',
    inventoryEffect: 'STOCK IN — finished-goods on-hand increases; raw reservations for the order are released when completed.',
    whenWrong: 'Receiving more than remaining is rejected: "Cannot receive X. Remaining quantity is Y."',
    next: 'Next → Costing / Complete',
    nextId: 'step-costing',
    openScreen: '/manufacturing/production/orders',
  },
  {
    id: 'step-rework',
    num: '17',
    title: 'Rework',
    summary: 'Fix failed output as its own tracked process.',
    phase: 'REWORK',
    module: 'Quality',
    inventory: 'NO STOCK EFFECT',
    icon: 'RotateCcw',
    childOf: 'Production Order',
    childLabel: 'Child record (rework)',
    purpose: 'When quality fails, a Rework record tracks how many units, why, and its cost. Lifecycle: Pending → In Progress → Completed.',
    where: { screen: 'Manufacturing → Quality → Rework', routes: ['/manufacturing/quality/rework'] },
    whatUserDoes: 'Create a Rework with quantity, reason, work center, operator and estimated/actual cost; then update the status from Pending to In Progress to Completed.',
    statusBefore: 'Rework Pending',
    action: 'Create Rework → Update status → Complete',
    statusAfter: 'Rework Completed',
    dataCreated: 'Rework record (reworkQuantity, reason, costs)',
    inventoryEffect: 'No stock effect by itself.',
    whenWrong: 'Rework is its own record — it does not automatically change the production-order status. Finish and re-inspect, then complete the MO.',
    next: 'Next → Final Quality / verification → Complete',
    nextId: 'step-complete',
    openScreen: '/manufacturing/quality/rework',
  },
  {
    id: 'step-scrap',
    num: '18',
    title: 'Scrap / Rejected',
    summary: 'Record production losses clearly.',
    phase: 'SCRAP',
    module: 'Manufacturing',
    inventory: 'RECORD',
    icon: 'CircleSlash2',
    childOf: 'Production Order',
    childLabel: 'Child records',
    purpose: 'Good, Rejected and Scrap are different. Rejected = produced but not accepted; Scrap = wasted material/output recorded as a loss with a reason and a cost.',
    where: { screen: 'Manufacturing → Materials → Scrap', routes: ['/manufacturing/materials/scrap'] },
    whatUserDoes: 'On the operation report enter good / rejected / scrap quantities. For separate loss tracking, add Scrap records (product, qty, reason, cost).',
    statusBefore: '(recorded during production)',
    action: 'Report quantities · Record Scrap',
    statusAfter: 'Outputs recorded; scrap logged',
    dataCreated: 'Scrap record (scrapNumber, reason, cost)',
    inventoryEffect: 'RECORD — a scrap record logs the loss and its cost; rejected units are not counted as good output. Material was already removed at Issue.',
    whenWrong: 'Reporting the same scrap/rejected on every operation would not double-count — the order uses the last operation that reported output.',
    next: 'Next → Output / FG Receipt',
    nextId: 'step-output',
    openScreen: '/manufacturing/materials/scrap',
  },
  {
    id: 'step-byproduct',
    num: '19',
    title: 'By-product',
    summary: 'Receive extra usable output into stock.',
    phase: 'BYPRODUCT',
    module: 'Manufacturing',
    inventory: 'STOCK IN',
    icon: 'PackagePlus',
    childOf: 'Production Order',
    childLabel: 'Child record (by-product)',
    purpose: 'A by-product is separate, valuable output produced alongside the main product. Unlike scrap it enters stock and adds value.',
    where: { screen: 'Manufacturing → Materials → By-products', routes: ['/manufacturing/materials/byproducts'] },
    whatUserDoes: 'Add a by-product line (product, quantity, warehouse, batch) and Receive it.',
    statusBefore: '(none)',
    action: 'Add by-product → Receive',
    statusAfter: 'By-product stock-in received',
    dataCreated: 'ByProduct record (productId, quantity, location, batch)',
    inventoryEffect: 'STOCK IN — on-hand of the by-product product increases in the receiving location.',
    next: 'Next → Costing / Complete',
    nextId: 'step-costing',
    openScreen: '/manufacturing/materials/byproducts',
  },
  {
    id: 'step-costing',
    num: '20',
    title: 'Costing',
    summary: 'See material + labor + machine + overhead → unit cost.',
    phase: 'COST',
    module: 'Costing',
    inventory: 'NO STOCK EFFECT',
    icon: 'Calculator',
    purpose: 'Show the production cost: material cost (BOM), labor and machine cost (Routing/work orders), overhead (10% of labor) and any scrap cost, then a unit cost.',
    where: { screen: 'Manufacturing → Costing · Production Order → Costing', routes: ['/manufacturing/costing', '/manufacturing/production/orders'] },
    whatUserDoes: 'Open the costing screen for the order to review material, labor, machine, overhead, additional/scrap, total and unit cost.',
    statusBefore: '(during/after production)',
    action: 'Review costing',
    statusAfter: 'Cost breakdown available',
    dataCreated: 'Cost breakdown (not a stock move)',
    inventoryEffect: 'No stock effect. Accounting postings depend on the accounting module invoicing/billing, not this screen.',
    whenWrong: 'Costs are estimated from BOM/Routing unless actual work-order hours and scrap costs are used.',
    next: 'Next → Complete',
    nextId: 'step-complete',
    openScreen: '/manufacturing/costing',
  },
  {
    id: 'step-complete',
    num: '21',
    title: 'Production Complete',
    summary: 'All planned quantity produced and finished goods received.',
    phase: 'COMPLETE',
    module: 'Manufacturing',
    inventory: 'NO STOCK EFFECT',
    icon: 'CheckCircle2',
    purpose: 'The order reaches Completed when the full planned quantity has been produced (remaining = 0) and finished goods have been received.',
    where: { screen: 'Production Order detail (via Complete & Receive FG)', routes: ['/manufacturing/production/orders'] },
    whatUserDoes: 'Ensure remaining = 0 and FG stock is received; the order becomes Completed. All remaining raw-material reservations are released.',
    statusBefore: 'In Progress / Partially Completed',
    action: 'Complete & Receive FG (remaining = 0)',
    statusAfter: 'Completed',
    dataCreated: 'producedQuantity = planned, remaining = 0, actualEndDate',
    inventoryEffect: 'FG already in; remaining raw reservations are released back to available.',
    whenWrong: 'If remaining > 0 the order is Partially Completed — continue the same MO or Close Short.',
    next: 'Next → Close',
    nextId: 'step-close',
    openScreen: '/manufacturing/production/orders',
  },
  {
    id: 'step-close',
    num: '22',
    title: 'Close',
    summary: 'Lock a completed order as final.',
    phase: 'CLOSE',
    module: 'Manufacturing',
    inventory: 'NO STOCK EFFECT',
    icon: 'Lock',
    purpose: 'Closing marks a Completed order as final. Closed is terminal — no further actions are allowed.',
    where: { screen: 'Production Order detail → Close', routes: ['/manufacturing/production/orders'] },
    whatUserDoes: 'Once Completed, press Close to make it terminal.',
    statusBefore: 'Completed',
    action: 'Close',
    statusAfter: 'Closed',
    dataCreated: 'Status history entry',
    inventoryEffect: 'No stock effect.',
    whenWrong: 'Completed and Closed Short are different endings. Completed = planned qty met; Closed Short = remaining intentionally closed with a reason.',
    next: 'Journey complete — order is Closed (or Closed Short / Cancelled).',
    openScreen: '/manufacturing/production/orders',
  },
];

// ============================================================
// Production Order statuses (as implemented in the backend workflow)
// ============================================================
export interface OrderStatus {
  name: string;
  meaning: string;
  reachedBy: string;
  canDo: string;
  cannot: string;
  inventory: string;
  color: string;
  transitions: string[];
}

export const ORDER_STATUSES: OrderStatus[] = [
  { name: 'Draft', meaning: 'Order created but not released. Nothing has been reserved or scheduled.', reachedBy: 'Creating a Production Order.', canDo: 'Edit, Release, Cancel.', cannot: 'Issue materials, start or receive FG.', inventory: 'No change.', color: '#7A8FA6', transitions: ['Release', 'Cancel'] },
  { name: 'Released', meaning: 'Material is reserved, Work Orders and WIP are created, the order is live.', reachedBy: 'Press Release (source warehouse required).', canDo: 'Start, Pause, Issue materials, Receive FG, Close Short, Cancel.', cannot: 'Go back to a locked-in reservation without re-receiving.', inventory: 'Reserved stock increases; available stock decreases (on-hand unchanged).', color: '#8E44AD', transitions: ['Start', 'Pause', 'Issue', 'Complete', 'Close Short', 'Cancel'] },
  { name: 'In Progress', meaning: 'Production has started; operators run the Work Orders/operations.', reachedBy: 'Press Start.', canDo: 'Run operations, Report quantities, Pause, Issue, Receive FG, Close Short, Cancel.', cannot: 'Nothing new — material already issued.', inventory: 'No new change beyond what Issue did.', color: '#0FA3E0', transitions: ['Pause', 'Complete', 'Close Short', 'Cancel'] },
  { name: 'Paused', meaning: 'Production is on hold (Hold/Pause) but not finished.', reachedBy: 'Press Pause (Hold).', canDo: 'Resume, Issue, Receive FG, Cancel.', cannot: 'Operation reporting while paused.', inventory: 'No new change.', color: '#F39C12', transitions: ['Resume', 'Complete', 'Cancel', 'Close Short'] },
  { name: 'Partially Completed', meaning: 'Some output was received but the planned quantity is not full yet.', reachedBy: 'Complete & Receive FG with remaining > 0.', canDo: 'Continue the SAME order to produce the remaining, receive again, Close Short, Cancel.', cannot: 'Nothing — you are expected to continue.', inventory: 'FG partly in stock; remaining reservations still apply.', color: '#F39C12', transitions: ['Complete again', 'Close Short', 'Cancel'] },
  { name: 'Completed', meaning: 'Full planned quantity produced and finished goods received (remaining = 0).', reachedBy: 'Complete & Receive FG with remaining = 0 (or auto-complete).', canDo: 'Close.', cannot: 'Close Short (unless remaining > 0), reopen operations.', inventory: 'FG in; remaining raw reservations released.', color: '#2ECC71', transitions: ['Close'] },
  { name: 'Closed', meaning: 'Final, terminal state after completion.', reachedBy: 'Press Close on a Completed order.', canDo: 'Nothing — it is final.', cannot: 'Anything.', inventory: 'None.', color: '#7A8FA6', transitions: [] },
  { name: 'Closed Short', meaning: 'The remaining quantity was intentionally closed without producing it.', reachedBy: 'Press Close Short with a mandatory reason.', canDo: 'Nothing — it is terminal.', cannot: 'Anything.', inventory: 'No new FG; remaining reservations released.', color: '#E67E22', transitions: [] },
  { name: 'Cancelled', meaning: 'Order aborted; reservations released back.', reachedBy: 'Press Cancel.', canDo: 'Nothing — it is terminal.', cannot: 'Anything.', inventory: 'Remaining reservations released.', color: '#E74C3C', transitions: [] },
];

// ============================================================
// Top-level journey (17 steps) — clickable at the top
// ============================================================
export const TOP_LEVEL: { num: string; label: string; detail: string; stepId: string }[] = [
  { num: '01', label: 'BUY', detail: 'Supplier + Purchase Order', stepId: 'step-supplier-purchase' },
  { num: '02', label: 'RECEIVE', detail: 'GRN / Goods Receiving', stepId: 'step-grn' },
  { num: '03', label: 'STOCK', detail: 'Raw material available', stepId: 'step-stock' },
  { num: '04', label: 'DEFINE BOM', detail: 'What material is required', stepId: 'step-bom' },
  { num: '05', label: 'DEFINE ROUTING', detail: 'How to produce', stepId: 'step-routing' },
  { num: '06', label: 'CREATE PRODUCTION ORDER', detail: 'Plan quantity', stepId: 'step-production-order' },
  { num: '07', label: 'RELEASE', detail: 'Live order', stepId: 'step-release' },
  { num: '08', label: 'RESERVE', detail: 'Hold material', stepId: 'step-reservation' },
  { num: '09', label: 'ISSUE', detail: 'Material out', stepId: 'step-issue' },
  { num: '10', label: 'PRODUCE', detail: 'Operations / Work Orders', stepId: 'step-operations' },
  { num: '11', label: 'REPORT OUTPUT', detail: 'Good / Rejected / Scrap', stepId: 'step-output' },
  { num: '12', label: 'QUALITY', detail: 'Inspection', stepId: 'step-quality' },
  { num: '13', label: 'REWORK/SCRAP/REJECT/BY-PRODUCT', detail: 'Handle exceptions', stepId: 'step-rework' },
  { num: '14', label: 'RECEIVE FG', detail: 'Finished goods in stock', stepId: 'step-fg' },
  { num: '15', label: 'COST', detail: 'Costing', stepId: 'step-costing' },
  { num: '16', label: 'COMPLETE', detail: 'Produced = planned', stepId: 'step-complete' },
  { num: '17', label: 'CLOSE', detail: 'Final / terminal', stepId: 'step-close' },
];

// ============================================================
// Child records of a Production Order (not separate order statuses)
// ============================================================
export const CHILD_RECORDS: { label: string; detail: string; openScreen?: string }[] = [
  { label: 'Reservation', detail: 'Material held for this order (Reserved / PartiallyReserved / Pending).', openScreen: '/manufacturing/materials/reservations' },
  { label: 'Material Issue', detail: 'Material exported to production (status Issued).', openScreen: '/manufacturing/materials/issues' },
  { label: 'Work Orders', detail: 'One per Routing operation (Pending / In Progress / Paused / Completed).', openScreen: '/manufacturing/production/work-orders' },
  { label: 'Inspection', detail: 'Quality result (Pending / Passed / Failed / Rework / Scrap).', openScreen: '/manufacturing/quality/inspections' },
  { label: 'Rework', detail: 'Units to fix (Pending → In Progress → Completed).', openScreen: '/manufacturing/quality/rework' },
  { label: 'Scrap', detail: 'Recorded loss + cost.', openScreen: '/manufacturing/materials/scrap' },
  { label: 'By-products', detail: 'Extra usable output received into stock.', openScreen: '/manufacturing/materials/byproducts' },
];

// ============================================================
// BOM example (Finished Product A)
// ============================================================
export const BOM_EXAMPLE = {
  product: 'Finished Product A',
  components: [
    { name: 'Raw Material A', qty: 10, unit: 'KG' },
    { name: 'Raw Material B', qty: 5, unit: 'KG' },
    { name: 'Packaging Box', qty: 2, unit: 'PCS' },
  ],
  units: 10,
};

// ============================================================
// "What happens if...?" decision branches
// ============================================================
export interface Decision {
  id: string;
  unless: string;
  then: string;
  openScreen?: string;
  tone: 'ok' | 'warn' | 'danger';
}

export const DECISIONS: Decision[] = [
  { id: 'd-no-stock', unless: 'Material is unavailable', then: 'You cannot reserve or issue it. Buy it and confirm a GRN first, then re-check stock and proceed.', openScreen: '/purchases/goodsRecieving', tone: 'danger' },
  { id: 'd-less', unless: 'Production produces less than planned', then: 'The order becomes Partially Completed with the remaining quantity. Continue the SAME production order to finish.', tone: 'warn' },
  { id: 'd-stop', unless: 'User wants to stop the remaining production', then: 'Close Short on the same order and enter a mandatory reason. The order is Closed Short (terminal).', openScreen: '/manufacturing/production/orders', tone: 'warn' },
  { id: 'd-qf', unless: 'Quality fails', then: 'Create a Rework (Pending → In Progress → Completed), rework the units, re-inspect, then complete the order. You may also decide to scrap.', tone: 'warn' },
  { id: 'd-pause', unless: 'An operation is paused', then: 'Pause (Hold) stops the Work Order / order. Resume returns it to In Progress.', tone: 'ok' },
  { id: 'd-resume', unless: 'Production is resumed', then: 'Resume moves the order back from Paused to In Progress and work continues.', tone: 'ok' },
  { id: 'd-reserved', unless: 'Material reserved but not issued', then: 'Reserved ≠ removed. Go to Materials → Issue to release the material to production (on-hand then decreases).', openScreen: '/manufacturing/materials/issues', tone: 'warn' },
  { id: 'd-cancel', unless: 'A Production Order is cancelled', then: 'Cancelled is terminal; the system releases the remaining material reservations.', openScreen: '/manufacturing/production/orders', tone: 'danger' },
  { id: 'd-received', unless: 'Finished Goods are received', then: 'FG on-hand increases by the good quantity; if remaining = 0 the order is Completed, otherwise Partially Completed.', tone: 'ok' },
  { id: 'd-byprod', unless: 'A by-product is created', then: 'The by-product product is received into the (finished goods) warehouse and its stock increases.', openScreen: '/manufacturing/materials/byproducts', tone: 'ok' },
];